server:
  port: 80
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://vimicro7001.com:7001/eureka/,http://vimicro7002.com:7002/eureka/,http://vimicro7003.com:7003/eureka/